### PR TITLE
Publishing JSDoc generated documentation to Doclets

### PR DESCRIPTION
**Pull request by keeganstreet**
The allows us to remove the generated artefact out of version control, and ensure that the documentation is automatically generated to be kept up to date.

### CODE REVIEW

**Comment by jennasalau** [comment]
Hey Keegan. This looks super cool!

How can I view the docs? If i go to https://doclets.io/DeloitteDigitalAPAC/DDBreakpoints i don't see any docs.. Or will they be generated once this branch merges.

**Comment by keeganstreet** [comment]
Hey @jennasalau, they only get published once we add the `.doclets.yml` file to our repo.

**Comment by keeganstreet** [comment]
Its a CI service just for docs!

**Review by jennasalau — APPROVED** [review]
Love it!

**Comment by dkeeghan** [comment]
Nice! Sounds like a good way forward

**Comment by keeganstreet** [comment]
Tada! https://doclets.io/DeloitteDigitalAPAC/DDBreakpoints/master

I think our Readme was referencing the Deloitte logo that I deleted, so I'll bring that back in.

**Pull request merged**
